class FileParams:
    type = "type"
    date = "date"
    time = "time"
    distance = "distance"
    climb = "climb"
    structure = "structure"
    pace = "pace"
    where = "where"
    notes = "notes"
    list = "list"

class Colnames:
    type = "type"
    date = "date"
    time = "time"
    distance = "distance"
    avg_pace = "avg_pace"
    climb = "climb"
    where = "where"
    notes = "notes"
    distE = "distE"
    distM = "distM"
    distT = "distT"
    distI = "distI"
    distR = "distR"
    paceE = "paceE"
    paceM = "paceM"
    paceT = "paceT"
    paceI = "paceI"
    paceR = "paceR"

class RunTypes:
    type = "type"
    E = "E"
    LE = "LE"
    M = "M"
    T = "T" 
    I = "I"
    H = "H"
    R = "R"
    C = "C"
    X = "X" 
    WU = "WU"
    CD = "CD"

class RunTypesLongName:
    type = "type"
    E = "easy"
    LE = "long easy"
    M = "marathon pace"
    T = "threshold pace" 
    I = "intervals"
    H = "hard"
    R = "repetitions"
    C = "carrera"
    X = "cross training" 
