class FileParams:
    type = "type"
    date = "date"
    time = "time"
    distance = "distance"
    climb = "climb"
    structure = "structure"
    pace = "pace"
    where = "where"

class RunTypes:
    type = "type"
    E = "E"
    LE = "LE"
    M = "M"
    T = "T" 
    I = "I"
    H = "H"
    R = "R"
    C = "C"
    X = "X" 
    WU = "WU"
    CD = "CD"

class RunTypesLongName:
    type = "type"
    E = "easy"
    LE = "long easy"
    M = "marathon pace"
    T = "threshold pace" 
    I = "intervals"
    H = "hard"
    R = "repetitions"
    C = "carrera"
    X = "cross training" 
